/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	core: [{ type: 'autogenerated', dirName: 'core' }],
	platform: [{ type: 'autogenerated', dirName: 'platform' }],
	integrations: [{ type: 'autogenerated', dirName: 'integrations' }],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

	// mySidebar: [{
	// 	type: 'category',
	// 	label: 'Getting Started',
	// 	items: ['restApi'],
	// }, {
	// 	type: 'category',
	// 	label: 'Docusaurus',
	// 	items: ['featurePreview'],
	// }]
}
